# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Site Settings
locale                   : "en-US"
title                    : "Sonali Sharma"
title_separator          : "|"
name                     : &name "Sonali Sharma"
description              : &description "AI Researcher at Stanford University"
url                      : "https://sonalisharma-3.github.io"
baseurl                  : ""
repository               : "sonalisharma-3/sonalisharma-3.github.io"
teaser                   :

# Site Author
author:
  name             : "Sonali Sharma"
  avatar           : "/images/profile.png"
  bio              : "Fulbright Scholar at Stanford University & Researcher in Medical AI & Radiology 🤖 "
  location         : "Vancouver / Palo Alto"
  employer         : "Stanford University"
  email            : "sonali3@stanford.edu"
  uri              :
  github           : "sonalisharma-3"
  linkedin         : "sonali-sharma-946936346"
  orcid            : "https://orcid.org/0000-0003-3803-0507"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
  - images
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # Main pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Site Settings
breadcrumbs              : false
words_per_minute         : 200
future                   : true
read_more                : "enabled"

# Comments
comments:
  provider               : false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
