# ==============================================================================
# SONALI SHARMA - AI SAFETY RESEARCHER
# Personal Academic Website Configuration
# ==============================================================================

# Site Settings
locale                   : "en-US"
title                    : "Sonali Sharma"
title_separator          : "|"
name                     : &name "Sonali Sharma"
description              : &description "AI Safety Researcher at Stanford University specializing in medical applications and AI governance"
url                      : "https://sonalisharma-3.github.io"
baseurl                  : ""
repository               : "sonalisharma-3/sonalisharma-3.github.io"
teaser                   : "/images/bio-photo.jpg"

# Site Author
author:
  name             : "Sonali Sharma"
  avatar           : "images/profile.png"
  bio              : "AI Safety Researcher at Stanford University • Medical AI & Radiology • Featured in MIT Technology Review & Computerworld"
  location         : "Stanford, CA"
  employer         : "Stanford University"
  email            : "sonali3@stanford.edu"
  uri              :
  
  # Academic & Professional Links
  googlescholar    : # Add your Google Scholar ID when available
  orcid            : "https://orcid.org/0000-0003-3803-0507"
  researchgate     : # Add if you have one
  
  # Code & Development
  github           : "sonalisharma-3"
  
  # Social & Professional Networks
  linkedin         : "sonali-sharma-946936346"
  twitter          : "sonalisharma336"
  
  # Other platforms (uncomment and add if needed)
  # mastodon         :
  # bluesky          :
  # youtube          :

# Navigation
main:
  - title: "About"
    url: /
  - title: "Research"
    url: /research/

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:path/

# Research Areas & Interests
research_interests:
  - "AI Safety in Healthcare"
  - "Medical Imaging & Radiology AI"
  - "AI Governance & Policy"
  - "Responsible AI Development"
  - "Healthcare AI Ethics"

# Featured Media Coverage
featured_media:
  - title: "AI companies have stopped warning you that their chatbots aren't doctors"
    outlet: "MIT Technology Review"
    date: "2025-07-21"
    url: "https://www.technologyreview.com/2025/07/21/1120522/ai-companies-have-stopped-warning-you-that-their-chatbots-arent-doctors/"
    description: "Analysis of how AI companies are removing medical disclaimers"
  - title: "AI chatbots ditch medical disclaimers, putting users at risk, study warns"
    outlet: "Computerworld"
    date: "2025"
    url: "https://www.computerworld.com/article/4026778/ai-chatbots-ditch-medical-disclaimers-putting-users-at-risk-study-warns.html"
    description: "Research on the risks of AI medical advice without proper warnings"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true

# Site Settings
breadcrumbs              : true
words_per_minute         : 200
future                   : true
read_more                : "enabled"
talkmap_link             : false

# Comments
comments:
  provider               : false

# SEO & Analytics
google_site_verification :
bing_site_verification   :
naver_site_verification  :

analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : # Add your Google Analytics ID
    anonymize_ip         : true

# Social Sharing
twitter:
  username               : "sonalisharma336"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
  
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  
keep_files:
  - .git
  - .svn
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache

# Plugin Settings
paginate: 5
paginate_path: /page:num/

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
  
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Custom Variables (for use in templates)
author_bio: "Sonali Sharma is an AI Safety Researcher at Stanford University, specializing in medical applications and radiology AI. Her work on AI governance and healthcare safety has been featured in leading publications including MIT Technology Review and Computerworld."

research_focus: "My research focuses on ensuring AI systems in healthcare are safe, reliable, and beneficial. I work at the intersection of AI safety, medical imaging, and policy, with particular attention to radiology applications and AI governance frameworks."
